### PR TITLE
[JENKINS-52751] Fix issues with JSON properties actions or foundFailureCauses missing from failure-cause REST response

### PR DESCRIPTION
**Pull request by getrostt**
Bugfix for JENKINS-52751

### CODE REVIEW

**Comment by getrostt** [comment]
Unfortunately the coverage reported by Jacoco does not show the full coverage for RunStatsListener#addBuildFailureCauses due to the usage of PowerMock (see https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo).

**Comment by getrostt** [comment]
@ssbarnea: When can I expect this PR to be merged and released?

**Comment by funkyfisch** [comment]
Can you give us an update on this? Is there a way to speed up the process/contribute? This is a really frustrating bug and I would be glad to be helpful in getting rid of it

**Comment by lucamilanesio** [comment]
I would say that a -0.3% is really negligible as a reduction in coverage. I'm happy to approve it.

**Comment by funkyfisch** [comment]
Thank you! Glad that we can now use the official release of the plugin again!

**Pull request merged**
