### PR TITLE
Update StatisticsConfiguration.java

### PR DESCRIPTION
**Pull request by rdpa**
Don't force appending a slash to URLs. Fixes https://issues.jenkins-ci.org/browse/JENKINS-54279

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @lucamilanesio is there anything else required to get this merged?

**Comment by lucamilanesio** [comment]
Sorry, I missed it, will have a look over the weekend.

**Comment by lucamilanesio** [comment]
@darxriggs it seems that @maximecharron put that logic in the past to fix a SonarQube issue (see 5bc4723eb472cbbc69d5af3436148dffed8cde15). Not sure exactly why a trailing slash should matter for SonarQube, but let's wait for a few days to see if @maximecharron remembers anything about it.

If I am not hearing anything from him within a few days, I'll merge it as-is.

**Comment by darxriggs** [comment]
@lucamilanesio I already had a look at the file's history to understand why the trailing slash functionality is in place. Unfortunately it's present since the initial commit 937faf671c60cd0b07a4319cfe2f3457bd9721de and therefore it's not clear why. The commit you referenced is about something different.

I strongly vote for this PR, not to automatically add a trailing slash. If a trailing slash is required for an endpoint a user can just configure it accordingly. Otherwise adding query parameters as described in the Jira ticket is not possible.

| Type | Value |
| --- | --- |
| original | http://example.org/some-path?param1=test |
| modified | http://example.org/some-path?param1=test/ |

**Pull request merged**
