### PR TITLE
Added functionality to publish events to AWS SNS

### PR DESCRIPTION
**Pull request by alexgandy**
Added SnsClientUtil, so that events can be published to SNS topics. Also added the ability to disable HTTP posts of events, in case you only want to use SNS.

New Admin Fields

(The SNS options are hidden under an "Advanced" button...expanded for this screenshot)

### CODE REVIEW

**Comment by maximecharron** [comment]
Pretty nice feature! Thanks Alex! I've been wanting to do something like it, but haven't had time yet. I'm happy to see this! I'll release it in a few!

**Comment by alexgandy** [comment]
Awesome, happy I could help out...also, thanks for the original plugin, it's been super helpful.

**Comment by maximecharron** [comment]
The original plugin is not from me. It's an old plugin that wasn't maintained. I just pimped it and gave it a new name ;)

**Comment by alexgandy** [comment]
Haha, nice...at least you're maintaining it

**Pull request merged**
